# Generated by Django 4.1.1 on 2022-09-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('B', 'Backend'), ('F', 'Frontend'), ('C', 'Cloud'), ('D', 'Devops')], max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_lancamento', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
