# Generated by Django 4.1.1 on 2022-09-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=100)),
            ],
        ),
    ]
