# Generated by Django 4.1.1 on 2022-10-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='titulo',
            new_name='nome',
        ),
    ]
